spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_42bd092ac8d298c?reconnect=true
    username: b9e9446e3ccdaf
    password: 261c48ef
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
upload:
  path: F:/uploads
server:
  port: 5000
amazonProperties:
  endpointUrl: https://s3.eu-west-3.amazonaws.com
  accessKey: AKIARBGCXCE43LRR42EO
  secretKey: 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
  bucketName: library-files-bucket


