spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: ./temp
  profiles:
    active: dev
server:
  port: 5000

