spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: ./temp
  profiles:
    active: prod
server:
  port: 5000


