spring:
  datasource:
    url: jdbc:mysql://aacapoos0ekokx.c904hqasbuic.eu-west-3.rds.amazonaws.com/ebdb
    username: libraryDbProd
    password: somestrongpassword
amazonProperties:
  endpointUrl: https://s3.eu-west-3.amazonaws.com
  accessKey: AKIARBGCXCE43LRR42EO
  secretKey: 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
  bucketName: library-prod-bucket

