spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_42bd092ac8d298c?reconnect=true
    username: b9e9446e3ccdaf
    password: 261c48ef
upload:
  path: F:/uploads
server:
  port: 5000
