spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_42bd092ac8d298c?reconnect=true
    username: b9e9446e3ccdaf
    password: 261c48ef
amazonProperties:
  endpointUrl: https://s3.eu-west-3.amazonaws.com
  accessKey: AKIARBGCXCE43LRR42EO
  secretKey: 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
  bucketName: library-files-bucket

